[env:lilygo_t3_v161]
extends = common
board = ttgo-lora32-v1
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_LILYGO_T3_V161
    -DAXLORA_HAS_OLED
    -Ivariants/lilygo_t3_v161
