[platformio]
default_envs = devkitv1_e22
extra_configs =
    variants/*/platformio.ini

[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^7.1.2
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -DCORE_DEBUG_LEVEL=0
build_unflags =
    -std=gnu++11
