[env:devkitv1_e22]
extends = common
board = esp32doit-devkit-v1
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_DEVKITV1_E22
    -DAXLORA_HAS_OLED
    -Ivariants/devkitv1_e22
