[env:tbeam_supreme_433]
extends = common
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_TBEAM_SUPREME_433
    -DAXLORA_HAS_OLED
    -DAXLORA_OLED_SH1106
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ivariants/tbeam_supreme_433
