[env:tbeam]
extends = common
board = ttgo-t-beam
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_TBEAM
    -DAXLORA_HAS_OLED
    -Ivariants/tbeam
