[env:heltec_v3]
extends = common
board = heltec_wifi_lora_32_V3
lib_deps =
    ${common.lib_deps}
    olikraus/U8g2
build_flags =
    ${common.build_flags}
    -DAXLORA_VARIANT_HELTEC_V3
    -DAXLORA_HAS_OLED
    -Ivariants/heltec_v3
