import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"BPQ / LinBPQ setup","description":"","frontmatter":{},"headers":[],"relativePath":"guide/bpq.md","filePath":"guide/bpq.md"}');
const _sfc_main = { name: "guide/bpq.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="bpq-linbpq-setup" tabindex="-1">BPQ / LinBPQ setup <a class="header-anchor" href="#bpq-linbpq-setup" aria-label="Permalink to &quot;BPQ / LinBPQ setup&quot;">​</a></h1><p>AXLoRaTNC behaves like a serial KISS TNC. BPQ sends complete AX.25 frames to the ESP32 over USB serial. AXLoRaTNC adds the AX.25 FCS, sends one complete AX.25 frame per LoRa packet, receives LoRa packets, checks FCS, and returns KISS frames to BPQ.</p><h2 id="tested-fast-setup" tabindex="-1">Tested fast setup <a class="header-anchor" href="#tested-fast-setup" aria-label="Permalink to &quot;Tested fast setup&quot;">​</a></h2><p>Use the same RF settings on every AXLoRaTNC node:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Frequency: 869.480 MHz</span></span>
<span class="line"><span>Bandwidth: 125 kHz</span></span>
<span class="line"><span>SF:        7</span></span>
<span class="line"><span>CR:        4/5</span></span>
<span class="line"><span>KISS baud: 115200</span></span></code></pre></div><p>For bench/lab testing, the fastest working TNC profile is:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>radio reset</span></span>
<span class="line"><span>profile fast</span></span>
<span class="line"><span>mode kiss</span></span></code></pre></div><p><code>profile fast</code> sets txdelay=0, persistence=255, slot=1, fulldup=0, duty=off.</p><div class="warning custom-block"><p class="custom-block-title">WARNING</p><p><code>profile fast</code> disables the firmware duty-cycle guard. Use it only on a dummy load or shielded lab setup. For normal RF operation, re-enable a legal duty-cycle setting.</p></div><h2 id="prepare-the-tnc" tabindex="-1">Prepare the TNC <a class="header-anchor" href="#prepare-the-tnc" aria-label="Permalink to &quot;Prepare the TNC&quot;">​</a></h2><p>Open a serial monitor at 115 200 baud:</p><div class="language-sh vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sh</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">./venv/bin/pio</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> device</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> monitor</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -b</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 115200</span></span></code></pre></div><p>Configure the node:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>mode console</span></span>
<span class="line"><span>callsign YOURCALL-0</span></span>
<span class="line"><span>radio reset</span></span>
<span class="line"><span>profile fast</span></span>
<span class="line"><span>radio</span></span>
<span class="line"><span>stats</span></span>
<span class="line"><span>mode kiss</span></span></code></pre></div><p>Expected <code>radio</code> output:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>freq=869.480 bw=125.0 sf=7 cr=4/5</span></span></code></pre></div><p>Expected <code>stats</code> timing:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>kiss_txdelay=0 p=255 slot=1 fulldup=0</span></span></code></pre></div><h2 id="serial-device" tabindex="-1">Serial device <a class="header-anchor" href="#serial-device" aria-label="Permalink to &quot;Serial device&quot;">​</a></h2><div class="language-sh vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sh</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">ls</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -l</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> /dev/serial/by-id/</span></span></code></pre></div><p>Prefer <code>/dev/serial/by-id/...</code> over <code>/dev/ttyUSB0</code> for a stable path after reboot. Use that path as <code>COMPORT</code> in <code>bpq32.cfg</code>.</p><h2 id="recommended-bpq-port-settings" tabindex="-1">Recommended BPQ port settings <a class="header-anchor" href="#recommended-bpq-port-settings" aria-label="Permalink to &quot;Recommended BPQ port settings&quot;">​</a></h2><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>TYPE=ASYNC</span></span>
<span class="line"><span>PROTOCOL=KISS</span></span>
<span class="line"><span>SPEED=115200</span></span>
<span class="line"><span>FULLDUP=0</span></span>
<span class="line"><span>TXDELAY=0</span></span>
<span class="line"><span>PERSIST=255</span></span>
<span class="line"><span>SLOTTIME=10</span></span>
<span class="line"><span>TXTAIL=0</span></span>
<span class="line"><span>MAXFRAME=1</span></span>
<span class="line"><span>PACLEN=80</span></span>
<span class="line"><span>FRACK=8000</span></span>
<span class="line"><span>RESPTIME=1000</span></span>
<span class="line"><span>RETRIES=10</span></span>
<span class="line"><span>NOKEEPALIVES=1</span></span></code></pre></div><ul><li><code>TXDELAY=0</code> — avoids a long wait before BPQ transmits.</li><li><code>PERSIST=255</code> — allows immediate transmit when the TNC queue is ready.</li><li><code>FULLDUP=0</code> — keeps the link half-duplex, important for LoRa.</li><li><code>MAXFRAME=1</code> — more reliable on LoRa; try <code>MAXFRAME=2</code> only after the link is stable.</li><li><code>PACLEN=80</code> — keeps LoRa airtime short; increase slowly if RSSI/SNR are strong.</li><li><code>NOKEEPALIVES=1</code> — reduces unnecessary KISS chatter.</li></ul><h2 id="complete-bpq32-cfg" tabindex="-1">Complete bpq32.cfg <a class="header-anchor" href="#complete-bpq32-cfg" aria-label="Permalink to &quot;Complete bpq32.cfg&quot;">​</a></h2><p>A complete example is in <code>examples/bpq32-axloratnc.cfg</code>. Copy it and edit:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>NODECALL   NODEALIAS   LOCATOR   COMPORT</span></span>
<span class="line"><span>IDMSG / BTEXT / INFOMSG / CTEXT</span></span></code></pre></div><div class="language-sh vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sh</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">sudo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> cp</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> examples/bpq32-axloratnc.cfg</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> /opt/linbpq/bpq32.cfg</span></span></code></pre></div><p>Restart LinBPQ after editing.</p><h2 id="basic-test" tabindex="-1">Basic test <a class="header-anchor" href="#basic-test" aria-label="Permalink to &quot;Basic test&quot;">​</a></h2><p>From another AX.25 / BPQ node:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>C YOURCALL-7</span></span></code></pre></div><p>Useful diagnostics on the AXLoRaTNC console:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>console</span></span>
<span class="line"><span>stats</span></span>
<span class="line"><span>radio</span></span>
<span class="line"><span>mheard</span></span>
<span class="line"><span>mode kiss</span></span></code></pre></div><p>Watch these counters: <code>txq</code> <code>queued</code> <code>deferred</code> <code>qdrops</code> <code>raw_tx</code> <code>raw_rx</code> <code>duty_drops</code>.</p><p>If <code>deferred</code> grows quickly, CSMA or duty-cycle is holding back frames. For the fast lab profile, <code>duty_drops</code> should stay at zero.</p><h2 id="extending-range-robustness" tabindex="-1">Extending range / robustness <a class="header-anchor" href="#extending-range-robustness" aria-label="Permalink to &quot;Extending range / robustness&quot;">​</a></h2><p>For longer range, use slower LoRa settings on every node:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>radio bw 62.5</span></span>
<span class="line"><span>radio sf 8</span></span>
<span class="line"><span>radio cr 8</span></span></code></pre></div><p>Adjust BPQ to be more patient:</p><div class="language-text vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>MAXFRAME=1</span></span>
<span class="line"><span>PACLEN=60</span></span>
<span class="line"><span>FRACK=12000</span></span>
<span class="line"><span>RESPTIME=1500</span></span>
<span class="line"><span>RETRIES=15</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/bpq.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const bpq = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  bpq as default
};
